# Generated by Django 3.2.12 on 2022-04-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='i_agree',
            field=models.BooleanField(default=False),
        ),
    ]
