# Generated by Django 3.2.12 on 2022-03-26 21:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import easy_thumbnails.fields
import phonenumber_field.modelfields
import tagify.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='company_logos', verbose_name='Logo')),
                ('industry', models.CharField(max_length=200, verbose_name='industry')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('public_company_info', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=10, verbose_name='Make company info public? (logo and name)')),
                ('communication_email', models.EmailField(max_length=254, verbose_name='Email for receiving CVs')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('city', models.CharField(choices=[('Al Anbar', 'Al Anbar'), ('Babylon', 'Babylon'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qadisiyyah', 'Al-Qadisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Halabja', 'Halabja'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], default='Baghdad', max_length=500, verbose_name='City')),
                ('country', django_countries.fields.CountryField(default='IQ', max_length=2, verbose_name='Country')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Is subscribed')),
                ('subscription_from', models.DateField(blank=True, null=True, verbose_name='Subscription From')),
                ('subscription_to', models.DateField(blank=True, null=True, verbose_name='Subscription To')),
                ('remaining_records', models.IntegerField(blank=True, null=True, verbose_name='Remaining Records')),
                ('remaining_jobs', models.IntegerField(blank=True, null=True, verbose_name='Remaining Jobs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subscription_plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=200, verbose_name='plan')),
                ('suggestions', models.IntegerField(verbose_name='suggestions')),
                ('jobs', models.IntegerField(verbose_name='Jobs')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('keywords', tagify.models.TagField(verbose_name='Position keywords')),
                ('job_description', ckeditor.fields.RichTextField(default='', verbose_name='Job Description')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Service contract', 'Service contract'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Internship', 'Internship')], default='Full-time', max_length=20, verbose_name='Employment Type')),
                ('date_opened', models.DateField(blank=True, null=True, verbose_name='Date opened')),
                ('date_closed', models.DateField(blank=True, null=True, verbose_name='Date closed')),
                ('city', models.CharField(choices=[('Al Anbar', 'Al Anbar'), ('Babylon', 'Babylon'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qadisiyyah', 'Al-Qadisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Halabja', 'Halabja'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], default='Baghdad', max_length=500, verbose_name='City')),
                ('country', django_countries.fields.CountryField(default='IQ', max_length=2, verbose_name='Country')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('nationality', models.CharField(choices=[('international', 'International'), ('national', 'National'), ('both', 'Both')], default='both', max_length=15, verbose_name='Nationality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('applied_candidates', models.ManyToManyField(blank=True, to='candidate.candidate', verbose_name='Applied Candidates')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_createdby', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_opened',),
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.subscription_plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('id', 'user')},
        ),
    ]
