# Generated by Django 3.2.12 on 2022-04-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_opened',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 15, 38, 45, 141611), verbose_name='Date opened'),
        ),
    ]
