# Generated by Django 3.2.9 on 2022-02-12 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('id', 'user')},
        ),
    ]
