# Generated by Django 3.2.12 on 2022-04-23 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20220423_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_opened',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date opened'),
        ),
    ]
