# Generated by Django 3.2.9 on 2022-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_unique_together'),
        ('employer', '0002_alter_employer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_candidates',
            field=models.ManyToManyField(blank=True, to='candidate.candidate', verbose_name='Applied Candidates'),
        ),
    ]
