# Generated by Django 3.2.9 on 2022-02-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20220215_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='communication_email',
            field=models.EmailField(max_length=254, verbose_name='Email for receiving CVs'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='public_company_info',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=10, verbose_name='Make company info public? (logo and name)'),
        ),
    ]
