# Generated by Django 3.2.15 on 2022-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_job_date_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='remaining_records',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Remaining Records'),
        ),
    ]
