# Generated by Django 3.2.9 on 2022-02-15 22:02

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20220216_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_closed',
            field=models.DateField(blank=True, null=True, verbose_name='Date closed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_opened',
            field=models.DateField(blank=True, null=True, verbose_name='Date opened'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Service contract', 'Service contract'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Internship', 'Internship')], default='Full-time', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default_currency='IQD', max_digits=10, null=True, verbose_name='Salary'),
        ),
    ]
