# Generated by Django 3.2.9 on 2022-02-15 11:31

from django.db import migrations, models
import django_countries.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20220215_1431'),
        ('employer', '0004_auto_20220214_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_candidates',
            field=models.ManyToManyField(blank=True, to='candidate.candidate', verbose_name='Applied Candidates'),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_closed',
            field=models.DateField(verbose_name='Date closed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_opened',
            field=models.DateField(verbose_name='Date opened'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Internship', 'Internship')], default='Full-time', max_length=15, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default_currency='IQD', max_digits=10, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='subscription_plan',
            name='plan',
            field=models.CharField(max_length=200, verbose_name='plan'),
        ),
    ]
