# Generated by Django 3.2.9 on 2022-02-26 07:26

from django.db import migrations
import djmoney.models.fields
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_auto_20220216_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=tagify.models.TagField(default='', verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription_plan',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=10, verbose_name='Price'),
        ),
    ]
