# Generated by Django 3.2.9 on 2022-02-26 13:17

from django.db import migrations, models
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20220226_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=tagify.models.TagField(verbose_name='Position keywords'),
        ),
    ]
