# Generated by Django 3.2.9 on 2022-02-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20220226_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-date_opened',)},
        ),
    ]
