# Generated by Django 3.2.9 on 2022-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='remaining_jobs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Remaining Jobs'),
        ),
    ]
