# Generated by Django 3.2.15 on 2023-07-06 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_job_employer'),
    ]

    operations = [
    ]
