# Generated by Django 3.2.15 on 2023-07-20 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20220618_2158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0008_auto_20230706_0116'),
    ]

    operations = [

    ]
