# Generated by Django 3.2.15 on 2023-07-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_auto_20220618_2158'),
        ('employer', '0009_auto_20230720_2318'),
    ]

    operations = [

        migrations.AddField(
            model_name='subscription_plan',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        )
    ]
