# Generated by Django 3.2.23 on 2023-11-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_auto_20231107_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='remaining_jobs',
        ),
    ]
