# Generated by Django 3.2.9 on 2021-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='college',
            new_name='specility',
        ),
        migrations.AddField(
            model_name='candidate',
            name='university',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
