# Generated by Django 3.2.9 on 2021-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20211107_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(default='', upload_to='media/cv'),
            preserve_default=False,
        ),
    ]
