# Generated by Django 3.2.9 on 2022-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20220216_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employer_industry',
            field=models.CharField(default='', max_length=50, verbose_name='Employer Industry'),
            preserve_default=False,
        ),
    ]
