# Generated by Django 3.2.9 on 2022-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expired_certificate',
            field=models.BooleanField(blank=True, null=True, verbose_name='Expired certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expire Date'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization'),
        ),
    ]
