# Generated by Django 3.2.9 on 2022-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(choices=[('Al Anbar', 'Al Anbar'), ('Babylon', 'Babylon'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qadisiyyah', 'Al-Qadisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Halabja', 'Halabja'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], default='Baghdad', max_length=500, verbose_name='Current City'),
        ),
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.CharField(max_length=500, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='city',
            field=models.CharField(max_length=500, verbose_name='City'),
        ),
    ]
