# Generated by Django 3.2.13 on 2022-06-18 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0004_alter_candidate_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(default='2cd475c8-33cf-4498-8f98-02da6dfd5ad6', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('id', 'user', 'email')},
        ),
    ]
