# Generated by Django 3.2.9 on 2021-11-09 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2000)]),
            preserve_default=False,
        ),
    ]
