# Generated by Django 3.2.9 on 2022-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20220213_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expired_certificate',
            field=models.BooleanField(default=False, verbose_name='Expired certificate'),
        ),
    ]
