# Generated by Django 3.2.9 on 2022-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20220221_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expired_certificate',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='This credential does not expire'),
        ),
    ]
