# Generated by Django 3.2.9 on 2022-01-04 20:22

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_graduation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('education_level', models.CharField(choices=[('1', 'Non-Degree Programme'), ('2', 'High School diploma'), ('3', 'Technical Diploma'), (
                    '4', 'Bachelors Degree'), ('5', 'Master Degree'), ('6', 'PhD Doctorate Degree')], max_length=1, verbose_name='Education Level')),
                ('country', django_countries.fields.CountryField(
                    max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('institution', models.CharField(
                    max_length=100, verbose_name='Institution')),
                ('original_title_of_the_qualification', models.CharField(
                    max_length=100, verbose_name='Original Title of the qualification')),
                ('main_subject', models.CharField(
                    max_length=100, verbose_name='Main subject')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('graduation_date', models.DateField(
                    verbose_name='Graduation Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='have_you_applied_here_before',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='have_you_worked_here_before',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='salary_desired',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='salary_desired_currency',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='specility',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='university',
        ),
        migrations.AddField(
            model_name='candidate',
            name='address1',
            field=models.CharField(
                default='', max_length=500, verbose_name='Address Line(1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='address2',
            field=models.CharField(
                default='', max_length=500, verbose_name='Address Line(2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='alternate_email_address',
            field=models.EmailField(
                default='', max_length=254, verbose_name='Alternative email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='', max_length=128, region=None, verbose_name='Conact phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='country_of_birth',
            field=django_countries.fields.CountryField(
                default='', max_length=2, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[(
                'MR', 'Mr.'), ('MS', 'Ms.')], default='M', max_length=2, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_level_of_education',
            field=models.CharField(choices=[('1', 'Non-Degree Programme'), ('2', 'High School diploma'), ('3', 'Technical Diploma'), ('4', 'Bachelors Degree'),
                                   ('5', 'Master Degree'), ('6', 'PhD Doctorate Degree')], default='', max_length=1, verbose_name='Highest level of education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_type',
            field=models.CharField(choices=[('H', 'Home'), ('M', 'Mobile'), (
                'W', 'Work')], default='', max_length=1, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='place_of_birth',
            field=models.CharField(
                default='', max_length=200, verbose_name='Place of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='postal_code',
            field=models.IntegerField(default=10001, validators=[django.core.validators.MaxValueValidator(
                10000), django.core.validators.MinValueValidator(99999)], verbose_name='Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='primary_nationality',
            field=django_countries.fields.CountryField(
                default='', max_length=2, verbose_name='Primary nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondary_nationality',
            field=django_countries.fields.CountryField(
                default='', max_length=2, verbose_name='Seondary nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(choices=[(
                'MR', 'Mr.'), ('MS', 'Ms.')], default='MR', max_length=2, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birthofdate',
            field=models.DateField(verbose_name='Birth of date'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=500, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='media/cv',
                                   verbose_name='CV File'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firtname',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='secondname',
            field=models.CharField(max_length=200, verbose_name='Second Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.ManyToManyField(
                to='candidate.education', verbose_name='Candidate Education'),
        ),
    ]
