# Generated by Django 3.2.9 on 2022-02-15 11:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_certificate_expired_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address1',
            field=models.CharField(
                max_length=500, verbose_name='Current address Line(1)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(
                max_length=500, verbose_name='Current city'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name='Current country'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country_of_birth',
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name='Country of Birth'),
        ),
    ]
