# Generated by Django 3.2.9 on 2022-01-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20220104_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='firtname',
            new_name='firstname',
        ),
    ]
