# Generated by Django 3.2.9 on 2022-02-24 11:25

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0007_auto_20220224_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='language',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='language',
            name='createdby',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='modifiedby',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='language_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
