# Generated by Django 3.2.9 on 2022-01-06 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_rename_firtname_candidate_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.')], default='Mr.', max_length=2, verbose_name='Title'),
        ),
    ]
