# Generated by Django 3.2.9 on 2022-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20220106_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
    ]
