# Generated by Django 3.2.9 on 2022-01-07 20:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20220106_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer', models.CharField(max_length=50, verbose_name='Employer')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('current_job', models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', verbose_name='Current Job')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('reason_for_leaving', models.CharField(max_length=200, verbose_name='Reason for leaving')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='Employment',
            field=models.ManyToManyField(to='candidate.employment', verbose_name='Employment History'),
        ),
    ]
