# Generated by Django 3.2.9 on 2022-02-24 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0009_auto_20220224_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='language',
            name='modifiedby',
        ),
        migrations.AddField(
            model_name='language',
            name='created',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='modified',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
