# Generated by Django 3.2.9 on 2022-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20220224_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
