# Generated by Django 3.2.9 on 2022-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_alter_employment_current_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='current_job',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Current Job'),
        ),
    ]
