# Generated by Django 3.2.9 on 2022-02-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_language_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('D', 'Divorced'), ('O', 'Other')], default='M', max_length=2, verbose_name='Gender'),
        ),
    ]
