# Generated by Django 3.2.9 on 2022-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_alter_candidate_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('-issue_date',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=2, verbose_name='Gender'),
        ),
    ]
