# Generated by Django 3.2.9 on 2022-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_alter_employment_current_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='current_job',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Current Job'),
        ),
    ]
