# Generated by Django 3.2.9 on 2022-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_alter_employment_current_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='reason_for_leaving',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reason for leaving'),
        ),
    ]
