# Generated by Django 3.2.9 on 2022-01-09 19:36

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20220108_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Employment',
            field=models.ManyToManyField(blank=True, to='candidate.employment', verbose_name='Employment History'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address Line(2)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='alternate_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternative email address'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Conact phone'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.ManyToManyField(blank=True, to='candidate.education', verbose_name='Candidate Education'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('M', 'Mobile'), ('W', 'Work')], max_length=1, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='secondary_nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Seondary nationality'),
        ),
    ]
