# Generated by Django 3.2.9 on 2022-01-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_auto_20220109_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos', verbose_name='Photo'),
        ),
    ]
