# Generated by Django 3.2.9 on 2022-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnail', verbose_name='Thumbnail image'),
        ),
    ]
