# Generated by Django 3.2.9 on 2022-01-30 21:50

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_candidate_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='photos/default.jpg', upload_to='photos'),
        ),
    ]
