# Generated by Django 3.2.9 on 2022-01-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_auto_20220131_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
