# Generated by Django 3.2.9 on 2022-02-03 07:26

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_alter_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='photos/default.jpg', upload_to='photos', verbose_name='Photo'),
        ),
    ]
