# Generated by Django 3.2.9 on 2022-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_auto_20220203_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], default='Single', max_length=10, verbose_name='Marital Status'),
        ),
    ]
