# Generated by Django 3.2.9 on 2022-02-04 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_candidate_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='job_description',
            field=models.CharField(default='', max_length=2000, validators=[django.core.validators.MinLengthValidator(200)], verbose_name='Job Description'),
            preserve_default=False,
        ),
    ]
