# Generated by Django 3.2.9 on 2022-02-05 20:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_employment_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='supervisor_email',
            field=models.EmailField(default='', max_length=100, verbose_name="Supervisor's Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='supervisor_name',
            field=models.CharField(default='', max_length=50, verbose_name="Supervisor's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='supervisor_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name="Supervisor's Phone"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='supervisor_title',
            field=models.CharField(default='', max_length=50, verbose_name="Supervisor's Title"),
            preserve_default=False,
        ),
    ]
