# Generated by Django 3.2.9 on 2022-02-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_auto_20220206_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=100, verbose_name='Certificate Name')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expire_date', models.DateField(verbose_name='Expire Date')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='certificate',
            field=models.ManyToManyField(blank=True, to='candidate.certificate', verbose_name='Certificates'),
        ),
    ]
