# Generated by Django 3.2.9 on 2022-02-06 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_auto_20220207_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='media/certificate', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'git'])], verbose_name='Attach File'),
        ),
    ]
