# Generated by Django 3.2.9 on 2022-02-07 20:16

from django.db import migrations
import tagify.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_certificate_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hobbies',
            field=tagify.models.TagField(default='', verbose_name='Hobbies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=tagify.models.TagField(default='', verbose_name='Skills'),
            preserve_default=False,
        ),
    ]
